# Generated by Django 5.0 on 2023-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание продукта', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=100, help_text='Цена продукта', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
